name: adpy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy==1.26.4
  - swig
  - boost-cpp
  - libboost
  - scipy 
  - meeko 
  - gemmi 
  # - autogrid
  - pip
  - pip:
      - vina
      - prody
      - rdkit-pypi
      # - adpy